### ISSUE TITLE
Fix Large Space between Recording Bar and Controls in Assessment.html

### ISSUE THREAD

**Issue by aedmondson** [zekehuntergreen/comsem#202]
This issue is present on the branch Placeholder-Pages. The last commit the issue does not occur on is f3c6525f9f0607aec7135a3aed152f5d2cb0ea3b. The commit directly following that commit is 078691a22bdfc67669772ba9a164310ee5971e30, which should be reviewed to find the error.

**Comment by dpmacisaac** [comment]
Fixed in issue #200
